// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD62hyDTfQunvgVU2x68jluH237aovaxL4',
    appId: '1:735541068067:web:2e76a2aeb4f32d83634c96',
    messagingSenderId: '735541068067',
    projectId: 'flutter-herodex3000',
    authDomain: 'flutter-herodex3000.firebaseapp.com',
    storageBucket: 'flutter-herodex3000.firebasestorage.app',
    measurementId: 'G-N6J44PPELK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKpr3wWUUjCPX7hMobgK8E7EPRuOXoeX8',
    appId: '1:735541068067:android:1d0eec15eb09f967634c96',
    messagingSenderId: '735541068067',
    projectId: 'flutter-herodex3000',
    storageBucket: 'flutter-herodex3000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0gK3M3_xdswdDwpaIaaufbeMikM2rG1Y',
    appId: '1:735541068067:ios:967b206f1a546dc0634c96',
    messagingSenderId: '735541068067',
    projectId: 'flutter-herodex3000',
    storageBucket: 'flutter-herodex3000.firebasestorage.app',
    iosBundleId: 'com.example.flutterHerodex3000',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0gK3M3_xdswdDwpaIaaufbeMikM2rG1Y',
    appId: '1:735541068067:ios:967b206f1a546dc0634c96',
    messagingSenderId: '735541068067',
    projectId: 'flutter-herodex3000',
    storageBucket: 'flutter-herodex3000.firebasestorage.app',
    iosBundleId: 'com.example.flutterHerodex3000',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD62hyDTfQunvgVU2x68jluH237aovaxL4',
    appId: '1:735541068067:web:d552a582a6397f94634c96',
    messagingSenderId: '735541068067',
    projectId: 'flutter-herodex3000',
    authDomain: 'flutter-herodex3000.firebaseapp.com',
    storageBucket: 'flutter-herodex3000.firebasestorage.app',
    measurementId: 'G-DXBF3NKDQW',
  );

}